---
- name: install apache
  apt: name=apache2 state=present
  become: yes

- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - libapache2-mod-php
    - php
    - php-mysql
  become: yes

- name: start Apache
  apt: name=apache2 state=present
  become: yes

- include_tasks: install_wp.yml
