---
- name: Create cache dir
  command: mkdir "{{ cache_dir }}"
  args:
    chdir: "{{ cache_dir }}"
    creates: "{{ cache_dir }}"
  become: yes
  
- name: Add repo
  apt_repository: repo='ppa:nginx/stable'
  become: yes
    
- name: Install nginx
  action: apt pkg=nginx-extras state=installed update_cache=true
  become: yes

- name: Disable def
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Copy cfg
  template:
    src: default.conf.j2 
    dest: /etc/nginx/conf.d/default.conf 
    mode: 0664
  notify: restart nginx
  become: yes

    
