---
# vars file for backend
frontend: 34.245.103.122
wp_dir: /var/www/wordpress
wp_site_title: Test2
wp_admin_user: admin
wp_admin_pass: adminpass
wp_admin_email: www@www.com

wpusers:
    - name: user1
      email: user1@www.com
      password: user1pass
      role: author
    - name: user2
      email: user2@www.com
      password: user2pass
      role: author
    - name: user3
      email: user3@www.com
      password: user3pass
      role: author